### ISSUE TITLE
undefined method `connect!' for ActionSubscriber::RabbitConnection:Module (NoMethodError)

### ISSUE THREAD

**Issue by brettallred** [moneydesktop/action_subscriber#21]
After merging 1.05 I am getting errors at

https://github.com/moneydesktop/action_subscriber/blob/master/lib/action_subscriber.rb#L68
https://github.com/moneydesktop/action_subscriber/blob/master/lib/action_subscriber.rb#L74

Looks like it got missed in the last update when we switched to publisher_connection & subscriber_connection

**Comment by mmmries** [comment]
Dangit! When I was removing that method I kept thinking to myself, "does this get used anywhere?" I grepped the ActionSubscriber codebase 3 times. But of course it was used in `babou`.

Do you think it would be better to add the method back in with a deprecation warning? Or should we just change the `ActionSubscriber` module to call `RabbitConnection.subscriber_connection` to force the connection to load up-front?

**Comment by brettallred** [comment]
I think just change it to use subscriber_connection unless you guys need backward compatibility in order to roll it out in your environment.

**Comment by mmmries** [comment]
:+1: I'll just change it in `babou` for now (and change babou to require `1.0.5+` of this gem)
